travis:
  secure:
    BINSTAR_TOKEN: d1361o7ulipFtSWETTyupO8nSEvjbZB9Cfsf+rtkHnUc7sGGvPa3jmV+BfaTiyJwPVjcnNm78oW+tKGQUjnPIy5xu72T5QBoy0/UwMBrLFkSHYym6e6WFMNpkXW7tv7eBlal5Adgj7ZkBMgFew/Hq01gJbzNW9lQLgEdmdNW4sCP5qrC0cI9fzUDWS0H1IyUt5QFmWK8DwlU6WiI2uTr9f9yHwfMjE9yneDMdVR+Lx/pi191FfGZu0mQr/h239H4an8qu4FJzbcAq7qOU0rinPaxBt4wAQBWz9ESLfB1owKf1RUiimgKb1Ys3XaLqhiXzq7e/NIudXUf+N//wP8bNLG44E2cAF0/AI3qaO+vNIJsZQpa298lcQfuOXhG1qrAtBuEDDe8lBJ+lSOgMoppqaMluWvEy/KDIRgRSDpc70I4f4YWmwlj1gPoOyBAs9mKWveuAoc7FTiACsQte01JGxsYPit37w665+ErKjRDZ4cKgtRXxcplaKG19TqsUAk0rXT6cs0N1ObyoHhhOMZSi+6JgiJGN6gVpsPPxFdnKRm9yXcyku4KDfYpE0CUoSsDvA1RKwImmNOLSjbRoeS9v0XAvPl/1umbdJFZlZ3FCBHYbHrfb/qKEyDUBeUX/BtM5ET7Pfr+FAZHKWNfxgGhxzrK7QwxfJAEMijpXJdpOew=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
